#!/usr/bin/env bash
# Updates the current state of the server
# Installs Nginx on the server
# Configures Nginx to include a custom X-Served-By header
# Overwrites the default page of Nginx
# Adds a redirection and a custom 404 page
# Restarts Nginx to apply changes

# Update and install Nginx
apt-get -y update
apt-get install -y nginx

# Overwrite the default Nginx page
echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to include the custom X-Served-By header
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm 404.html index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=-VGIt10m9VQ;
    }
    location /xyz {
        return 404;
    }
    error_page 404 /404.html;
}
EOF

# Restart Nginx to apply the changes
sudo service nginx restart
