#!/usr/bin/env bash
# Setup haproxy on server lb-01 to serve web-01 and web-02.
# Configure Nginx to return a custom header with the hostname.

sudo apt-get -y update
sudo apt-get -y install nginx haproxy

# Configure Nginx to include the X-Served-By header
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    location / {
        add_header X-Served-By "$HOSTNAME";
        root /var/www/html;
        index index.html;
    }
}' | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Backup original config
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

echo \
"
frontend lb-frontend
        bind *:80
        mode http
        default_backend lb-backend
backend lb-backend
        balance roundrobin
        server web-01 52.70.84.210:80 check
        server web-02 52.202.28.73:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply changes
sudo service haproxy restart
